###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Geaorge Mendel",
    "age": 81,
    "email": "geaorgemendel@email.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/63a5cfb451d3b0576c8ed340 HTTP/1.1

###
PUT http://localhost:9000/api/users/63a5cfb451d3b0576c8ed340 HTTP/1.1
Content-Type: application/json

{
    "name": "George Mendel",
    "age": 81,
    "email": "georgemendel@email.com"
}

###
DELETE http://localhost:9000/api/users/63a5cfb451d3b0576c8ed340 HTTP/1.1

